name: pull-request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code:
    uses: cyberuni/.github/.github/workflows/pnpm-verify.yml@chore/setup-node-pnpm-action
    with:
      skip-playwright: true
