name: release
on:
  push:
    branches: [main]

jobs:
  code:
    uses: cyberuni/.github/.github/workflows/pnpm-verify.yml@main

  release:
    uses: cyberuni/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit
